#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: cmake
# autospec version: v21
# autospec commit: f4a13a5
#
# Source0 file verified with key 0xBB463350D6EF31EF (heiko@shruuf.de)
#
Name     : kwalletmanager
Version  : 24.12.1
Release  : 79
URL      : https://download.kde.org/stable/release-service/24.12.1/src/kwalletmanager-24.12.1.tar.xz
Source0  : https://download.kde.org/stable/release-service/24.12.1/src/kwalletmanager-24.12.1.tar.xz
Source1  : https://download.kde.org/stable/release-service/24.12.1/src/kwalletmanager-24.12.1.tar.xz.sig
Source2  : BB463350D6EF31EF.pkey
Summary  : No detailed summary available
Group    : Development/Tools
License  : BSD-3-Clause CC0-1.0 GPL-2.0 GPL-3.0 LGPL-2.0
Requires: kwalletmanager-bin = %{version}-%{release}
Requires: kwalletmanager-data = %{version}-%{release}
Requires: kwalletmanager-lib = %{version}-%{release}
Requires: kwalletmanager-license = %{version}-%{release}
Requires: kwalletmanager-locales = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : buildreq-kde
BuildRequires : extra-cmake-modules-data
BuildRequires : gnupg
BuildRequires : kconfig-dev
BuildRequires : kcoreaddons-dev
BuildRequires : kcrash-dev
BuildRequires : kdbusaddons-dev
BuildRequires : ki18n-dev
BuildRequires : kio-dev
BuildRequires : kservice-dev
BuildRequires : kstatusnotifieritem-dev
BuildRequires : kwallet-dev
BuildRequires : qt6base-dev
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
No detailed description available

%package bin
Summary: bin components for the kwalletmanager package.
Group: Binaries
Requires: kwalletmanager-data = %{version}-%{release}
Requires: kwalletmanager-license = %{version}-%{release}

%description bin
bin components for the kwalletmanager package.


%package data
Summary: data components for the kwalletmanager package.
Group: Data

%description data
data components for the kwalletmanager package.


%package doc
Summary: doc components for the kwalletmanager package.
Group: Documentation

%description doc
doc components for the kwalletmanager package.


%package lib
Summary: lib components for the kwalletmanager package.
Group: Libraries
Requires: kwalletmanager-data = %{version}-%{release}
Requires: kwalletmanager-license = %{version}-%{release}

%description lib
lib components for the kwalletmanager package.


%package license
Summary: license components for the kwalletmanager package.
Group: Default

%description license
license components for the kwalletmanager package.


%package locales
Summary: locales components for the kwalletmanager package.
Group: Default

%description locales
locales components for the kwalletmanager package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) BB463350D6EF31EF' gpg.status
%setup -q -n kwalletmanager-24.12.1
cd %{_builddir}/kwalletmanager-24.12.1
pushd ..
cp -a kwalletmanager-24.12.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1736485665
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
pushd ../buildavx2/
mkdir -p clr-build-avx2
pushd clr-build-avx2
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
%cmake ..   -G 'Unix Makefiles'
make  %{?_smp_mflags}
popd
popd

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1736485665
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/kwalletmanager
cp %{_builddir}/kwalletmanager-%{version}/CMakePresets.json.license %{buildroot}/usr/share/package-licenses/kwalletmanager/29fb05b49e12a380545499938c4879440bd8851e || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/CC0-1.0.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/GPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/GPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/3e8971c6c5f16674958913a94a36b1ea7a00ac46 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/GPL-3.0-only.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/2123756e0b1fc8243547235a33c0fcabfe3b9a51 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/LGPL-2.0-only.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/LGPL-2.0-or-later.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/a4c60b3fefda228cd7439d3565df043192fef137 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/7d9831e05094ce723947d729c2a46a09d6e90275 || :
cp %{_builddir}/kwalletmanager-%{version}/LICENSES/LicenseRef-KDE-Accepted-GPL.txt %{buildroot}/usr/share/package-licenses/kwalletmanager/7d9831e05094ce723947d729c2a46a09d6e90275 || :
export GOAMD64=v2
pushd ../buildavx2/
GOAMD64=v3
pushd clr-build-avx2
%make_install_v3  || :
popd
popd
GOAMD64=v2
pushd clr-build
%make_install
popd
%find_lang kcmkwallet
%find_lang kwalletmanager
## install_append content
#mv %{buildroot}/etc/dbus-1/* %{buildroot}/usr/share/dbus-1/
## install_append end
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/V3/usr/lib64/libexec/kf6/kauth/kcm_kwallet_helper5
/usr/lib64/libexec/kf6/kauth/kcm_kwallet_helper5

%files bin
%defattr(-,root,root,-)
/V3/usr/bin/kwalletmanager5
/usr/bin/kwalletmanager5

%files data
%defattr(-,root,root,-)
/usr/share/applications/kwalletmanager5-kwalletd.desktop
/usr/share/applications/org.kde.kwalletmanager.desktop
/usr/share/dbus-1/services/org.kde.kwalletmanager.service
/usr/share/dbus-1/system-services/org.kde.kcontrol.kcmkwallet5.service
/usr/share/dbus-1/system.d/org.kde.kcontrol.kcmkwallet5.conf
/usr/share/icons/hicolor/128x128/apps/kwalletmanager.png
/usr/share/icons/hicolor/128x128/apps/kwalletmanager2.png
/usr/share/icons/hicolor/16x16/apps/kwalletmanager.png
/usr/share/icons/hicolor/16x16/apps/kwalletmanager2.png
/usr/share/icons/hicolor/22x22/actions/wallet-closed.png
/usr/share/icons/hicolor/22x22/actions/wallet-open.png
/usr/share/icons/hicolor/22x22/apps/kwalletmanager.png
/usr/share/icons/hicolor/32x32/apps/kwalletmanager.png
/usr/share/icons/hicolor/32x32/apps/kwalletmanager2.png
/usr/share/icons/hicolor/48x48/apps/kwalletmanager.png
/usr/share/icons/hicolor/48x48/apps/kwalletmanager2.png
/usr/share/icons/hicolor/64x64/apps/kwalletmanager.png
/usr/share/icons/hicolor/64x64/apps/kwalletmanager2.png
/usr/share/metainfo/org.kde.kwalletmanager5.appdata.xml
/usr/share/polkit-1/actions/org.kde.kcontrol.kcmkwallet5.policy
/usr/share/qlogging-categories6/kwalletmanager.categories

%files doc
%defattr(0644,root,root,0755)
/usr/share/doc/HTML/ca/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/ca/kwalletmanager/index.docbook
/usr/share/doc/HTML/de/kwalletmanager/edit1.png
/usr/share/doc/HTML/de/kwalletmanager/edit2.png
/usr/share/doc/HTML/de/kwalletmanager/first-open-request.png
/usr/share/doc/HTML/de/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/de/kwalletmanager/index.docbook
/usr/share/doc/HTML/de/kwalletmanager/kwalletmanager.png
/usr/share/doc/HTML/de/kwalletmanager/openwallet-request.png
/usr/share/doc/HTML/de/kwalletmanager/save-login-information.png
/usr/share/doc/HTML/en/kwalletmanager/application-request-to-open-wallet.png
/usr/share/doc/HTML/en/kwalletmanager/error-nokey.png
/usr/share/doc/HTML/en/kwalletmanager/first-open-request.png
/usr/share/doc/HTML/en/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/en/kwalletmanager/index.docbook
/usr/share/doc/HTML/en/kwalletmanager/key-selection.png
/usr/share/doc/HTML/en/kwalletmanager/kwallet-access-control.png
/usr/share/doc/HTML/en/kwalletmanager/kwallet-applications.png
/usr/share/doc/HTML/en/kwalletmanager/kwallet-edit.png
/usr/share/doc/HTML/en/kwalletmanager/kwalletmanager.png
/usr/share/doc/HTML/en/kwalletmanager/openwallet-request.png
/usr/share/doc/HTML/en/kwalletmanager/save-login-information.png
/usr/share/doc/HTML/en/kwalletmanager/wallet-encryption-selection.png
/usr/share/doc/HTML/es/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/es/kwalletmanager/index.docbook
/usr/share/doc/HTML/fr/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/fr/kwalletmanager/index.docbook
/usr/share/doc/HTML/it/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/it/kwalletmanager/index.docbook
/usr/share/doc/HTML/nl/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/nl/kwalletmanager/index.docbook
/usr/share/doc/HTML/pt/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/pt/kwalletmanager/index.docbook
/usr/share/doc/HTML/pt_BR/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/pt_BR/kwalletmanager/index.docbook
/usr/share/doc/HTML/ru/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/ru/kwalletmanager/index.docbook
/usr/share/doc/HTML/sl/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/sl/kwalletmanager/index.docbook
/usr/share/doc/HTML/sr/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/sr/kwalletmanager/index.docbook
/usr/share/doc/HTML/sr@latin/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/sr@latin/kwalletmanager/index.docbook
/usr/share/doc/HTML/sv/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/sv/kwalletmanager/index.docbook
/usr/share/doc/HTML/tr/kwalletmanager/application-request-to-open-wallet.png
/usr/share/doc/HTML/tr/kwalletmanager/error-nokey.png
/usr/share/doc/HTML/tr/kwalletmanager/first-open-request.png
/usr/share/doc/HTML/tr/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/tr/kwalletmanager/index.docbook
/usr/share/doc/HTML/tr/kwalletmanager/key-selection.png
/usr/share/doc/HTML/tr/kwalletmanager/kwallet-access-control.png
/usr/share/doc/HTML/tr/kwalletmanager/kwallet-applications.png
/usr/share/doc/HTML/tr/kwalletmanager/kwallet-edit.png
/usr/share/doc/HTML/tr/kwalletmanager/kwalletmanager.png
/usr/share/doc/HTML/tr/kwalletmanager/openwallet-request.png
/usr/share/doc/HTML/tr/kwalletmanager/save-login-information.png
/usr/share/doc/HTML/tr/kwalletmanager/wallet-encryption-selection.png
/usr/share/doc/HTML/uk/kwalletmanager/index.cache.bz2
/usr/share/doc/HTML/uk/kwalletmanager/index.docbook
/usr/share/doc/HTML/uk/kwalletmanager/kwalletmanager.png
/usr/share/doc/HTML/uk/kwalletmanager/openwallet-request.png
/usr/share/doc/HTML/uk/kwalletmanager/save-login-information.png

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwallet5.so
/usr/lib64/qt6/plugins/plasma/kcms/systemsettings_qwidgets/kcm_kwallet5.so

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/kwalletmanager/2123756e0b1fc8243547235a33c0fcabfe3b9a51
/usr/share/package-licenses/kwalletmanager/29fb05b49e12a380545499938c4879440bd8851e
/usr/share/package-licenses/kwalletmanager/3e8971c6c5f16674958913a94a36b1ea7a00ac46
/usr/share/package-licenses/kwalletmanager/7d9831e05094ce723947d729c2a46a09d6e90275
/usr/share/package-licenses/kwalletmanager/82da472f6d00dc5f0a651f33ebb320aa9c7b08d0
/usr/share/package-licenses/kwalletmanager/a4c60b3fefda228cd7439d3565df043192fef137

%files locales -f kcmkwallet.lang -f kwalletmanager.lang
%defattr(-,root,root,-)

